### ISSUE TITLE
Cannot save the newly created component

### ISSUE THREAD

**Issue by Shababsoft** [xjsender/haoide#115] opened 2016-05-23 07:49 UTC
@xjsender I am not able to save a newly created component (i.e. classes, trigger). Every time when I create a class or a trigger and try to save after modification, I am getting the following message: `The component is not in active project`. This is happening since last update.

**Comment by xjsender** [comment] 2016-05-23 08:09
@Shababsoft , yes, it's a bug and fixed in the latest commit.

**Comment by Shababsoft** [comment] 2016-05-23 08:16
Thanks @xjsender, please can you provide settings to switch between **Async** and **Sync** for save, fetch or other actions in next release. I am getting the conflict popup every-time I save a component, when I am working on bugs I normally have to save a class couple of times in one minute.

Thanks again.

**Comment by xjsender** [comment] 2016-05-23 08:23
@Shababsoft , it's easy to switch between sync and async, I will investigate on this.

**Comment by xjsender** [comment] 2016-05-23 08:33
@Shababsoft , you always got the conflict warning, which is a bug and caused by ``the metadata cache solution`` .

**Comment by xjsender** [comment] 2016-05-23 13:31
@Shababsoft , I released ``v3.4.1``, can you help me check whether your problem are fixed?

**Comment by Shababsoft** [comment] 2016-05-23 13:39
@xjsender  Thanks, both issues has been resolved.

**Closed** 2016-05-23 13:41 UTC
Labels: bug, fixed
