### ISSUE TITLE
Problem with save/deploy class to server

### ISSUE THREAD

**Issue by maksimln** [xjsender/haoide#16] opened 2015-04-16 16:05 UTC
global with sharing class MyController extends TestPackage.TestController{
.....
}

I try to save MyController.cls file and get error
Compile Error for MyController.cls: Package Visibility: Type is not visible TestPackage.TestController at line 1 column -1

TestPackage has no TestController class in version 1.0 but this class present in 1.1 version

All work correct through SF UI.

**Comment by xjsender** [comment] 2015-04-16 23:32
@maksimln , how can I replicate your problem? can you give me the sample code?

**Comment by xjsender** [comment] 2015-04-20 03:51
@maksimln , can you give the complete sample code?

**Comment by maksimln** [comment] 2015-04-20 08:21
- Create/Upload managed package (v 1.0) (package prefix name TestPakcage)
- Install to another org

- Back to managed package org and add class with code  
global with sharing TestController {
       global TestController(){
       }
      global virtual void foo(){}
}

- Create/Upload managed package with this class (v 1.1)
- Install this package (v.1.1) to the second org (where package v1.0 installed )
- Create class with following code in the second org
global with sharing NewTestController extends TestPakcage.TestController {
       global NewTestController {}
}
- Try to save this file through Sublime 
---->> ERROR


Feel free to ask if need more information.

Thanks,
Maksim

**Comment by xjsender** [comment] 2015-04-20 08:31
@maksimln , did you try to use ``Deploy to Server`` command but not ```Save to Server``` to save this class file? I think it may be ```Tooling API``` bug.

**Comment by maksimln** [comment] 2015-04-20 08:40
Deploy to Server work fine

**Comment by maksimln** [comment] 2015-04-20 08:42
Also try to edit metadata

<?xml version="1.0" encoding="UTF-8"?>
<ApexClass xmlns="http://soap.sforce.com/2006/04/metadata">
    <apiVersion>33.0</apiVersion>
    <packageVersions>
        <majorNumber>1</majorNumber>
        <minorNumber>1</minorNumber>
        <namespace>TestPakcage</namespace>
    </packageVersions>
    <status>Active</status>
</ApexClass>

And try use API 32v and 33v

**Comment by maksimln** [comment] 2015-04-20 08:45
This error in SF UI too if package version set to 1.0v for this class

**Comment by xjsender** [comment] 2015-04-20 09:15
@maksimln , I can't get your point, is this a bug?

**Comment by maksimln** [comment] 2015-04-20 09:19
Yes, it is bug

**Comment by xjsender** [comment] 2015-04-20 09:22
@maksimln , I think it is a ```Tooling API``` bug, because ```Deploy to Server``` works fine but ```Save to Server``` don't work.

I don't know how to fix issue like this, I will flag this issue as ```Tooling API``` bug and wontfix.

**Comment by dimitrisuls** [comment] 2015-07-06 14:50
@xjsender 

I'm facing the same issue sadly.
Deploy to server also has this issue..

It's as if the API doesn't recoginize the managed package's code.

I plan on using this tool, and possibly our whole team.
It seems a lot better than MavensMate!

**Comment by xjsender** [comment] 2015-07-06 15:17
@dimitrisuls , can you describe your situation? I need a simple way to reproduce this problem.

Actually, I didn't put much focus on development of managed package, I am always focused on unmanaged package development

**Comment by dimitrisuls** [comment] 2015-07-07 08:32
@xjsender 

I'm just trying to save an Apex Class which references other classes which are managed in a Managed Package.

For our team this is very important since in every project we do we reference our Utility managed package to speed productivity.

I'm not sure what could be the issue here. Perhaps you have more knowledge to examine this issue?

**Comment by xjsender** [comment] 2015-07-07 14:18
@dimitrisuls , I will try to install a managed package and reference the class in it, maybe I can replicate this issue.

**Comment by dimitrisuls** [comment] 2015-07-07 14:51
@xjsender 

OK that would be awesome thanks a lot!

**Comment by xjsender** [comment] 2015-07-07 14:55
@dimitrisuls , is your problem same with @maksimln ? I just reference a class method in managed package, there is no problem, I am trying to replicate the issue of maksimln's as the steps described by him.

**Comment by dimitrisuls** [comment] 2015-07-07 14:57
What I do is extend from class in a Managed Package, and override some virtual methods.

The error I receive is that the method cannot be overriden since it has no ancestor method.

**Comment by xjsender** [comment] 2015-07-07 15:10
@dimitrisuls , If I use ``save to server`` command to save below class, we will get error message 
``Error: Compile Error: NewTestController: Non-virtual and non-abstract type cannot be extended: haoliu.TestController at line 1 column 14``

```java
// haoliu is a managed package
// There has a virtual method in haoliu.TestController
public class NewTestController extends haoliu.TestController {
}
```

However, if I use ``deploy to server`` command to save it, we will get error message ``Compile Error for NewTestController.cls: Package Visibility: Type is not visible: testcontroller at line 1 column -1``

**Comment by dimitrisuls** [comment] 2015-07-07 15:11
That's because you should make haolui.TestController a virtual class! :)

Then you will receive another error.. Similar to the one below, I think.

**Comment by xjsender** [comment] 2015-07-07 15:12
@dimitrisuls , thanks for your help, I will update it and then try it as your way.

**Comment by xjsender** [comment] 2015-07-07 15:19
@dimitrisuls , after I add the virtual notation for the class in managed package, I will ``Compile Error for NewTestController.cls: Package Visibility: Type is not visible: testcontroller at line 1 column -1`` when using ``save to server`` by tooling api, however, no error by ``deploy to server``, I didn't get the same error message with yours.

It seems a tooling api bug, I will try deeper investiage on it.

**Comment by dimitrisuls** [comment] 2015-07-07 15:23
OK. That's what I thought as well.

I think you have to submit the metadata of the apex-class as well. Providing the referenced managed packages + their version. Although the metadata API seems to do that automatically, the tooling api doesn't?.. I'm not sure

**Comment by xjsender** [comment] 2015-07-07 15:24
@dimitrisuls , @maksimln , I get the point from mavensmate community, you can check [this link](https://github.com/joeferraro/MavensMate-SublimeText/issues/333), it should be a tooling api bug.

When you ran into this problem, you should use ``deploy to server`` command but not ``save to server``, however, there is no keymap for ``deploy to server``, actually, you can define your own keymap.

Thanks.

**Comment by xjsender** [comment] 2015-07-07 15:26
@dimitrisuls , the tooling api works in different way comparing with metadata api.

**Comment by xjsender** [comment] 2015-07-07 15:28
As you saw in the below picture, you should use ``deploy to server`` command but not ``save to server``, 
``deploy to server`` uses ``Metadata API``, ``save to server`` uses ``Tooling API``.

![image](https://cloud.githubusercontent.com/assets/1450977/8549848/a5b5e234-24ff-11e5-88ab-3f20cffddc8c.png)

**Comment by dimitrisuls** [comment] 2015-07-07 15:29
@xjsender I think there should be a workaround.

Aside.io also uses the Tooling API, and I can save classes referencing the Tooling API without error..

Please see the following documentation:
http://salesforce.stackexchange.com/questions/43964/how-to-set-managed-packaged-versions-for-apex-class-with-tooling-api

**Comment by xjsender** [comment] 2015-07-07 15:32
@dimitrisuls , thanks, I am reading it.

**Comment by xjsender** [comment] 2015-07-07 16:15
@dimitrisuls , I tried to hard code as the workaround, I always get this error message ``Cannot deserialize instance of complexvalue from START_OBJECT value { at [line:1, column:178]``, there is no official document about the REST method of this ``metadata`` attribute, so I decide to give up to continue on this workaround, if your have idea on it, please help me, thanks.

```python
        data = {
            "ContentEntityId": component_id,
            "MetadataContainerId": container_id,
            "Metadata": {
                "apiVersion": 34,
                "status": "Active",
                "packageVersions": {
                    "majorNumber": 1,
                    "minorNumber": 2,
                    "namespace": "haoliu"
                }
            },
            "Body": body
        }
```

**Comment by dimitrisuls** [comment] 2015-07-07 16:31
@xjsender 

Thanks again for taking the time for this.

What does line 178 correspond with?

**Comment by dimitrisuls** [comment] 2015-07-07 16:36
@xjsender 

I think the packageVersions should be an array? Since mulitple managed packages could be references.
Please try that..

**Comment by xjsender** [comment] 2015-07-08 01:16
@dimitrisuls , I don't know What line 178 is correspond with. I will try your way tonight.

**Comment by dimitrisuls** [comment] 2015-07-08 07:09
@xjsender 

I think you should simply change it to the following:

```
data = {
            "ContentEntityId": component_id,
            "MetadataContainerId": container_id,
            "Metadata": {
                "apiVersion": 34,
                "status": "Active",
                "packageVersions": {
                    "majorNumber": 1,
                    "minorNumber": 2,
                    "namespace": "haoliu"
                }
            },
            "Body": body
        }
```

to

```
data = {
            "ContentEntityId": component_id,
            "MetadataContainerId": container_id,
            "Metadata": {
                "apiVersion": 34,
                "status": "Active",
                "packageVersions": [{
                    "majorNumber": 1,
                    "minorNumber": 2,
                    "namespace": "haoliu"
                }]
            },
            "Body": body
        }
```

**Comment by xjsender** [comment] 2015-07-08 10:27
@dimitrisuls , yes, sure, I will try that.

**Comment by xjsender** [comment] 2015-07-08 12:29
@dimitrisuls , you are right about the metdata format but still have ``Compile Error for NewTestController.cls: Package Visibility: Type is not visible: testcontroller at line 1 column -1``

**Comment by maksimln** [comment] 2015-07-08 12:33
haoliu.TestController is public or global?

**Comment by dimitrisuls** [comment] 2015-07-08 12:33
@maksimln 

Good catch..

**Comment by xjsender** [comment] 2015-07-08 12:55
## haoliu.TestController:
```java
global with sharing virtual class TestController {
    global TestController() {
        Account acc = [SELECT Id, Name FROM Account lIMIT 1];
    }
    
    global virtual void foo() {

    }
}
```

## NewTestController
```java
public class NewTestController extends haoliu.TestController {
    public NewTestController() {
        System.debug('abc');
    }
}
```

**Comment by xjsender** [comment] 2015-07-08 12:57
### Package Information
![image](https://cloud.githubusercontent.com/assets/1450977/8570574/d6f4179e-25b3-11e5-8678-10f23a50667c.png)

**Comment by maksimln** [comment] 2015-07-08 13:54
What metadata for NewTestController class when you save it?

**Comment by xjsender** [comment] 2015-07-08 14:15
@maksimln , metadata? what do you mean?

**Comment by dimitrisuls** [comment] 2015-07-09 08:13
@xjsender 

I'm not sure what could be the issue now.. You're sure you've installed the latest version on the target-org right?

**Comment by xjsender** [comment] 2015-07-09 09:00
@dimitrisuls , Yes, I installed the latest one.

**Comment by maksimln** [comment] 2015-07-09 10:55
May be need to use MetadataContainerMemberId instead of MetadataContainerId on ContainerAsyncRequest?

**Comment by maksimln** [comment] 2015-07-09 11:01
MetadataContainerMemberId in ApexClassMember response

curl -H 'X-PrettyPrint: 1' -H 'Authorization: Bearer 00....' \
    -H 'Content-Type: application/json' \
    -d '{ "ContentEntityId" : "01p28000001nwuNAAQ",
    	  "MetadataContainerId": "1dc280000006EtVAAU", "Metadata": {
                "apiVersion": 33,
                "status": "Active",
                "packageVersions": [
	                {
	                    "majorNumber": 1,
	                    "minorNumber": 2,
	                    "namespace": "package_prefix"
	                }
                ]
            },
          "Body" : "public with sharing class TestCtrl {public TestCtrl() { return;} public void foo(){}}" }' \
    https://c9.salesforce.com/services/data/v33.0/tooling/sobjects/ApexClassMember

{
  "id" : "40028000000N8TkAAK", ---- it is MetadataContainerMemberId
  "success" : true,
  "errors" : [ ]
}

**Comment by maksimln** [comment] 2015-07-09 11:02
Can you try it?

**Comment by xjsender** [comment] 2015-07-09 12:43
@maksimln , 

I tried to post below data to ``/services/data/v34.0/tooling/sobjects/ContainerAsyncRequest``, I get error message ``null is not a valid containerId.: Metadata Container ID``

```json
{
    "MetadataContainerMemberId": "40090000000RCJnAAO",
    "IsCheckOnly": false
}
```

and then, I tried to post below data to ``/services/data/v34.0/tooling/sobjects/ContainerAsyncRequest``, I got error message ``Package Visibility: Type is not visible: testcontroller at line 1 column -1``

```json
{
    "MetadataContainerId": "1dc90000000IIeLAAW",
    "MetadataContainerMemberId": "40090000000RCJnAAO",
    "IsCheckOnly": false
}
```

**Comment by maksimln** [comment] 2015-07-09 13:34
Specify a MetadataContainerId or a MetadataContainerMemberId, but not both.

**Comment by xjsender** [comment] 2015-07-09 13:40
@maksimln , I did, because it doesn't work, so I tried to add both.

**Comment by dimitrisuls** [comment] 2015-07-14 13:38
Hi @xjsender 

Any update? I'd be very excited to use Haoide if this would work.. This is a primary feature for me.

**Comment by maksimln** [comment] 2015-07-14 14:01
@dimitrisuls Did you try to use eclipse IDE for this case?

**Comment by dimitrisuls** [comment] 2015-07-14 14:39
@xjsender 

Yes. Eclipse IDE + Force.com IDE gives the same error.. :(

The only IDE who seems able to do this is aside.io. But they're not open-source.

**Comment by xjsender** [comment] 2015-07-14 14:40
@dimitrisuls , so busy these days, I will try to investigate it now.

**Comment by dimitrisuls** [comment] 2015-07-14 14:42
@xjsender 

I understand. I appreciate your time and effort tremendously.

**Comment by xjsender** [comment] 2015-07-14 14:56
I just tried to set related ``apiVersion`` to ``28``, not work with the same error message.

**Comment by xjsender** [comment] 2015-07-14 15:51
I checked almost available documents or blogs on it, I can't find a good way to solve this issue, I think aside is using ``Metdata API`` to bypass this issue.

@dimitrisuls , I will stop to investigate on this issue util [idea](https://success.salesforce.com/ideaView?id=08730000000l8a5AAA) metioned in this [blog](http://www.tgerm.com/2014/05/managed-package-extension-developer-console-chaos-package-visiblity-type-not-visible.html) is delivered.

Thanks for your support on this plugin.

**Comment by maksimln** [comment] 2015-07-15 09:17
I have suggestion
Can you do bind hotkey (like alt+cmd+d) for fast deploy current class to current instance?

I mean when I try to deploy the current class I should select an instance and it is not comfortable.

Thanks

**Comment by xjsender** [comment] 2015-07-15 09:30
@maksimln , it is reasonable request, can you log a new issue for this?

**Comment by maksimln** [comment] 2015-07-15 10:16
new issue: https://github.com/xjsender/haoide/issues/54

**Comment by xjsender** [comment] 2015-07-15 10:53
@maksimln , thanks.

**Comment by xjsender** [comment] 2016-06-05 12:25
I think this issue is already fixed by salesforce, you can have a try.

**Closed** 2016-06-05 12:27 UTC
Labels: fixed, tooling API bug

**Comment by dimitrisuls** [comment] 2016-06-05 12:48
Thanks will try tomorrow!
